Missing force parameter in starters
This is passed in by lax_response_adapter, but was not accepted.

After this, the workflow gets to RewriteEIF but fails there
```
2018-01-12T11:52:48Z ERROR worker_11736 Exception when rewriting EIF
Traceback (most recent call last):
  File "/opt/elife-bot/activity/activity_RewriteEIF.py", line 45, in
do_activity
    eif_json = eif_provider.read_eif_from_s3(conn, eif_bucket, eif_location)
  File "/opt/elife-bot/provider/eif.py", line 46, in read_eif_from_s3
    data = json.loads(json_input)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```