Token seems to be built with concatenation
Making the token building more robust so that when there is an integer hiding in these fields, it survives and we can see the failure when validating the message rather than:
```
2016-10-19T15:39:54Z ERROR worker_304 Exception when Preparing Publish action for Lax
Traceback (most recent call last):
  File "/opt/elife-bot/activity/activity_PublishToLax.py", line 57, in do_activity
    article_id, run, expanded_folder, version, status, eif_location, 'publish')
  File "/opt/elife-bot/provider/lax_provider.py", line 71, in prepare_action_message
    'token': lax_token(run, version, expanded_folder, status, eif_location)
  File "/opt/elife-bot/provider/lax_provider.py", line 86, in lax_token
    '"status": "' + status + '"}'
TypeError: coercing to Unicode: need string or buffer, int found
```