More robust handling of renaming error
In a test an XML file was empty, the exception got caught but this handler didn't produce a permanent failure because

```
2017-05-17T09:13:08Z ERROR worker_1791 error executing activity
activity_ApplyVersionNumber
Traceback (most recent call last):
File "worker.py", line 71, in work
    activity_result = activity_object.do_activity(data)
File "/opt/elife-bot/activity/activity_ApplyVersionNumber.py", line 80, in do_activity " message:" + e.message)
    TypeError: cannot concatenate 'str' and 'ExpatError' objects
```